 /*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusScreenshot -p dbusscreenshot com.deepin.DeepinScreenshot.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
*/  

#include "environment_file.h"

// Default constructor
EnvironmentFile::EnvironmentFile()
    : envFile()
    , flag(false)
{
}

// Copy constructor
EnvironmentFile::EnvironmentFile(const EnvironmentFile &rhs) :
    envFile(rhs.envFile),
    flag(rhs.flag)
{
}

// Copy assignment
EnvironmentFile &EnvironmentFile::operator=(const EnvironmentFile &rhs)
{
    if (this != &rhs) {
        envFile = rhs.envFile;
        flag = rhs.flag;
    }
    return *this;
}

// Destructor
EnvironmentFile::~EnvironmentFile() {}

// Register meta type
void EnvironmentFile::registerMetaType()
{
    qRegisterMetaType<EnvironmentFile>("EnvironmentFile");
    qDBusRegisterMetaType<EnvironmentFile>();
    qRegisterMetaType<EnvironmentFileList>("EnvironmentFileList");
    qDBusRegisterMetaType<EnvironmentFileList>();
}

// Print EnvironmentFile object to debug stream
QDebug &operator<<(QDebug &debug, const EnvironmentFile &file)
{
    debug << file.envFile << " flag: " << file.flag;
    return debug;
}

// Print EnvironmentFile object to DBus argument object
QDBusArgument &operator<<(QDBusArgument &argument, const EnvironmentFile &file)
{
    argument.beginStructure();
    argument << file.envFile << file.flag;
    argument.endStructure();
    return argument;
}

// Print EnvironmentFile object to data stream
QDataStream &operator<<(QDataStream &stream, const EnvironmentFile &file)
{
    stream << file.envFile << file.flag;
    return stream;
}

// Read EnvironmentFile object from DBus argument
const QDBusArgument &operator>>(const QDBusArgument &argument, EnvironmentFile &file)
{
    argument.beginStructure();
    argument >> file.envFile >> file.flag;
    argument.endStructure();
    return argument;
}

// Read EnvironmentFile object from data stream
const QDataStream &operator>>(QDataStream &stream, EnvironmentFile &file)
{
    stream >> file.envFile >> file.flag;
    return stream;
}
