.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-system-monitor" "1" "2021-3-8" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-system-monitor \- system monitor for deepin.
.SH SYNOPSIS
deepin-system-monitor
.SH DESCRIPTION
A system monitor tool.
.PP
System Monitor is a system tool monitoring and managing hardware load, program running and system services. It's capable to real-time monitor CPU status, memory footprint, and upload/download speed, manage system and application processes, search and force end processes as well.
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-system-monitor
.SH AUTHOR
.PP
.B deepin-system-monitor
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT leiyu@\:uniontech.com
Lei Yu
.ME
for the Debian Project (but may be used by others)
