 /*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusScreenshot -p dbusscreenshot com.deepin.DeepinScreenshot.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
*/  

#ifndef SYSTEMMONITORDBUSADAPTOR_H
#define SYSTEMMONITORDBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

class SystemMonitorDBusAdaptor :  public QObject, protected QDBusContext
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.SystemMonitorPluginPopup")

public:
    explicit SystemMonitorDBusAdaptor(QObject *parent = nullptr);
    virtual ~SystemMonitorDBusAdaptor();

public:
public slots:
    Q_SCRIPTABLE void slotShowOrHideSystemMonitorPluginPopupWidget();

signals:
    Q_SCRIPTABLE void sigSendShowOrHideSystemMonitorPluginPopupWidget();
};

#endif // SYSTEMMONITORDBUSADAPTOR_H
