 /*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusScreenshot -p dbusscreenshot com.deepin.DeepinScreenshot.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
*/  

#include "systemmonitordbusadaptor.h"


SystemMonitorDBusAdaptor::SystemMonitorDBusAdaptor(QObject *parent) : QObject(parent)
{

}

SystemMonitorDBusAdaptor::~SystemMonitorDBusAdaptor()
{

}

void SystemMonitorDBusAdaptor::slotShowOrHideSystemMonitorPluginPopupWidget()
{
    emit sigSendShowOrHideSystemMonitorPluginPopupWidget();
}

