/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.freedesktop.systemd1.Manager.xml -p systemd1_manager_interface -i unit_info.h -c Systemd1ManagerInterface
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "systemd1_manager_interface.h"

/*
 * Implementation of interface class Systemd1ManagerInterface
 */

Systemd1ManagerInterface::Systemd1ManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

Systemd1ManagerInterface::~Systemd1ManagerInterface()
{
}

